const mongoose= require('mongoose')

const schema= new mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        pincode:{
            type:String,
            required:true
        },
        phoneNo:{
            type:String,
            required:true
        }
    },
    orderItems:[{
        name:{
            type:String,
            default:""
        },
        price:{
            type:Number,
            default:""
        },
        quantity:{
            type:Number,
            default:""
        },
        image:{
            type:String,
            default:""
        },
        productId:{
            type:String,
            default:""
        }
    }],
        user:{
            type:mongoose.Schema.ObjectId,
            ref:"E-User",
            required:true
        },
    paymentInfo:{
        id:{
            type:String,
            default:""
        },
        status:{
            type:String,
            default:""
        },
        paidAt:{
            type:Date,
            default:""
        },
        itemsPrice:{
            type:Number,
            default:0
        },
        taxPrice:{
            type:Number,
            required:true,
            default:0
        },
        shippingPrice:{
            type:Number,
            required:true,
            default:0
        },
        totalPrice:{
            type:Number,
            required:true,
            default:0
        },
        orderStatus:{
            type:String,
            required:true,
            default:'processing'
        },
        deliveredAt:Date,
    }
},
{
    timestamps:true
}
)
module.exports=mongoose.model('userOrder',schema);